accent = "#7daea3"
cursor = "#f8f8f0"
foreground = "#e5e5e5"
background = "#23262e"
selection_foreground = "#23262e"
selection_background = "#d65d0e"

    color0 = "#000000"
    color1 = "#f92672"
    color2 = "#00e8c6"
    color3 = "#ffe66d"
    color4 = "#7cb7ff"
    color5 = "#c74ded"
    color6 = "#96e072"
    color7 = "#e5e5e5"
    color8 = "#666666"
    color9 = "#ee5d43"
    color10 = "#96e072"
    color11 = "#f39c12"
    color12 = "#7cb7ff"
    color13 = "#ff00aa"
    color14 = "#00e8c6"
    color15 = "#e5e5e5"
